### ISSUE TITLE
segfault in LT

### ISSUE THREAD

**Issue by ftyers** [ixa-ehu/matxin#5]
```
$ cat /tmp/es | /home/fran/local/bin/Analyzer -f /home/fran/local/share/matxin/config/es-eu.cfg | LT -f /home/fran/local/share/matxin/config/es-eu.cfg
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 0)
Avortat
```

```
#0  0x00007ffff2e66107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff2e674e8 in __GI_abort () at abort.c:89
#2  0x00007ffff3751b3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff374fbb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff374fc01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff374fe19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff37a5cdf in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000000000043ceb1 in _M_check (__s=0x44ce17 "basic_string::erase", __pos=18446744073709551615, this=0x7fffffffd760) at /usr/include/c++/4.9/bits/basic_string.h:324
#8  erase (__n=1, __pos=18446744073709551615, this=0x7fffffffd760) at /usr/include/c++/4.9/bits/basic_string.h:1383
#9  init_lexInfo (name=L"chunkType", fitxName="/home/fran/local/share/matxin/dict/es-eu/chunk_type.dat") at data_manager.cc:745
#10 0x000000000040bc93 in main (argc=<optimized out>, argv=<optimized out>) at LT.cc:683
```

**Comment by ftyers** [comment]
```
diff --git a/src/data_manager.cc b/src/data_manager.cc
index 29fc85d..3446646 100644
--- a/src/data_manager.cc
+++ b/src/data_manager.cc
@@ -741,9 +741,13 @@ void init_lexInfo(wstring name, string fitxName)
         i--;
       }
     }
-    if (lerro[lerro.size()-1] == L' ' or lerro[lerro.size()-1] == L'\t')
-      lerro.erase(lerro.size()-1,1);
-
+    if (lerro[lerro.size()-1] == L' ' or lerro[lerro.size()-1] == L'\t') 
+    {
+      int x = int(lerro.size()) - 1;
+      if(x == 0) {
+        lerro.erase(x,1); 
+      }
+    }
     size_t pos = lerro.find(L"\t");
     if (pos == wstring::npos)
       continue;

```

This fixes it, but I don't know why. Someone else should take a look.
